from typing import Protocol, Any

class SklearnClassifier(Protocol):
    """Protocol defining the interface for a scikit-learn compatible classifier"""

    def fit(self, X: Any, y: Any) -> "SklearnClassifier": ...
    def score(self, X: Any, y: Any) -> float: ...
    def predict(self, X: Any) -> Any: ...
